pipeline {
    agent any 
    stages {
        stage('Compile and Clean') { 
            steps {
                sh "mvn clean compile"
            }
        }
       

        stage('deploy') { 
            steps {
                sh "mvn package"
            }
        }


        stage('Build Docker image'){
            steps {
              
                sh 'docker build -t  dvazhava/docker1:latest  .'
            }
        }

        stage('Docker Login'){
            
            steps {
                 withCredentials([string(credentialsId: 'DockerId', variable: 'Dockerpwd')]) {
                    sh "docker login -u dvazhava -p ${divya2521997}"
                }
            }                
        }

        stage('Docker Push'){
            steps {
                sh 'docker push dvazhava/docker1:latest'
            }
        }
        
        stage('Docker deploy'){
            steps {
               
                sh 'docker run -itd -p  8095:8095 dvazhava/docker1:latest'
            }
        }

        
        stage('Archving') { 
            steps {///////////////
                 archiveArtifacts '**/target/*.jar'
            }
        }
    }
}